### ISSUE TITLE
Copyright concerns

### ISSUE THREAD

**Issue by lodenrogue** [trakBan/spongebob-cli#11]
Cool project. Any ideas for how to deal with copyright concerns?

**Comment by trakBan** [comment]
I doubt that you can watch classical spongebob "legally" anymore. I would say this is in a grey zone such as other movie CLIs which you can use to watch older movies and animes.

**Comment by tacohitbox** [comment]
Actually they're all available on Paramount+ and Amazon Prime. However, I think the site that hosts the episodes would be under hot water, not this repo.

**Comment by lodenrogue** [comment]
I think this repo will be viewed as facilitating access to copyrighted materials. Like an app that lets you download anime or movies that are not in the public domain. There have been DMCA takedown notices in the past for even more general apps than this.

**Comment by tacohitbox** [comment]
Although I think it's stupid that *code that accesses the sites for you* shouldn't face a DMCA since it doesn't actually contain copyrighted content, you're probably right.
