### ISSUE TITLE
episode 30 doesn't work 

### ISSUE THREAD

**Issue by ItsiAdam** [trakBan/spongebob-cli#24]
As per README.md.
Could you clarify why this is??

**Comment by thelittlebug** [comment]
im not a spongebob expert, but maybe its because there is no video?

https://www.megacartoons.net/no-free-rides/

**Comment by Ali-TM-original** [comment]
> Someone should make an RFC pull request for supporting alternative sources

I have also lately noticed the site bugging and going down frequently. This may be cause of the cli lol

**Comment by trakBan** [comment]
> I have also lately noticed the site bugging and going down frequently. This may be cause of the cli lol

yea it was a pretty small site that i doubt it can handle the bandiwith.

**Comment by trakBan** [comment]
> Someone should make an RFC pull request for supporting alternative sources

I doubt that i will do this, but i can make a server where i host all of those episodes so there will be no website going down issue.
