### ISSUE TITLE
Episode 31 downloads a Pink Panther episode instead (name conflict?)

### ISSUE THREAD

**Issue by charldeonfls** [trakBan/spongebob-cli#35]
When I try to download Episode 31, it downloads a Pink Panther episode instead.

`!/content/spongebob-cli/spongebob-cli --download 31`
`The-Pink-Panther-Pink-Suds-The-Pink-Panther-Pink-Suds.mp4`

It's possible that the titles are conflicting, since they have a really similar name:
https://www.imdb.com/title/tt0170392/
https://www.imdb.com/title/tt0769437/

**Comment by trakBan** [comment]
This is a problem from a website spongeob-cli scrapes its videos from. I cannot really do anything about it.
