### ISSUE TITLE
Remove Unnecessary SystemExit Calls

### ISSUE THREAD

**Issue by ilystsov** [trakBan/spongebob-cli#37]
In the `spongebob-cli` file, there are several instances of raising `SystemExit` exception to terminate the program, like in this line:
https://github.com/trakBan/spongebob-cli/blob/54b730f4a22f63193359faaef4db9ced8768c8d8/spongebob-cli#L140
Using this method to terminate the program may be considered overkill. In my opinion, it is better to use `return` statement to achieve the same result, keeping the code more simple.

**Comment by trakBan** [comment]
Sorry for the late reply, I have refactored that part of the code now, thanks.
