### ISSUE TITLE
Only 96 episodes

### ISSUE THREAD

**Issue by Oklati** [trakBan/spongebob-cli#39]
I can only watch the first 96 episodes. from episode 0 to 95.
the first being "Help Wanted" with index 0 and the last being "Squilliam Returns" with index 95. so something like "spongebob-cli -p 98" gives error "IndexError: list index out of range".

Btw, thank you for the fix of previous issues! :)

**Comment by trakBan** [comment]
The website where spongebob-cli scrapes their videos changed to ajax to load dynamically. spongebob-cli now can only scrape up to 32 videos with one request, making a need for multiple requests at a time which is quite taxing for the website and performance of spongebob-cli. This currently is only a workaround that problem and in the future all episodes should be listed.
