### ISSUE TITLE
using colored when it is missing

### ISSUE THREAD

**Issue by kamilko2006kk** [trakBan/spongebob-cli#6]
in https://github.com/trakBan/spongebob-cli/blob/main/spongebob-cli#L5-L11 if colored is missing code will use colorer to tell that colored is missing and fail because colored is missing

**Comment by kamilko2006kk** [comment]
also it should exit with error instead of continuing with missing libs

**Comment by trakBan** [comment]
Yea, it doesnt make sense @totensee fixed it.
